# Generated by Django 5.2.8 on 2025-11-22 17:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=200)),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_barras', models.IntegerField(unique=True)),
                ('nome_produto', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('preco_compra', models.FloatField()),
                ('preco_venda', models.FloatField()),
                ('tamanho', models.IntegerField(blank=True, null=True)),
                ('peso', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('data_nasc', models.DateField()),
                ('sexo', models.CharField(max_length=10)),
                ('login', models.CharField(max_length=50, unique=True)),
                ('senha', models.CharField(max_length=50)),
                ('pontos', models.IntegerField(default=0)),
                ('descontos', models.IntegerField(default=0)),
                ('endereco', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao.endereco')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('data_nasc', models.DateField()),
                ('sexo', models.CharField(max_length=10)),
                ('login', models.CharField(max_length=50, unique=True)),
                ('senha', models.CharField(max_length=50)),
                ('salario', models.FloatField()),
                ('matricula', models.IntegerField(unique=True)),
                ('filial', models.CharField(max_length=100)),
                ('endereco', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao.endereco')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('data_nasc', models.DateField()),
                ('sexo', models.CharField(max_length=10)),
                ('login', models.CharField(max_length=50, unique=True)),
                ('senha', models.CharField(max_length=50)),
                ('salario', models.FloatField()),
                ('matricula', models.IntegerField(unique=True)),
                ('carga_horaria', models.CharField(max_length=50)),
                ('num_caixa', models.IntegerField(blank=True, null=True)),
                ('endereco', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao.endereco')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=0)),
                ('limite_minimo', models.IntegerField(default=10)),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestao.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrega', models.DateTimeField(default=django.utils.timezone.now)),
                ('valor_total', models.FloatField()),
                ('nota_fiscal', models.CharField(default='000', max_length=100)),
                ('produtos', models.ManyToManyField(related_name='entregas', to='gestao.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_venda', models.DateTimeField(default=django.utils.timezone.now)),
                ('valor_total', models.FloatField(default=0.0)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao.cliente')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestao.funcionario')),
                ('produtos', models.ManyToManyField(through='gestao.ItemVenda', to='gestao.produto')),
            ],
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.venda'),
        ),
    ]
