# Generated by Django 5.2.8 on 2026-10-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvenda',
            name='preco_unitario',
            field=models.FloatField(default=0),
        ),
    ]
